name: hrvault

services:

  postgres:
    image: postgres:17
    container_name: hrvault-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - hrvault-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hrvault-pgadmin

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      - hrvault-network

  minio:
   image: quay.io/minio/aistor/minio:latest
   container_name: hrvault-minio

   restart: unless-stopped

   command:
     - minio
     - server
     - /data
     - --console-address
     - ":9001"
     - --license
     - /minio.license

   environment:
     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

   ports:
     - "9000:9000"
     - "9001:9001"

   volumes:
     - minio_data:/data
     - ./minio.license:/minio.license:ro

   networks:
     - hrvault-network

  redis:
    image: redis:7-alpine
    container_name: hrvault-redis

    restart: unless-stopped

    command: redis-server --requirepass ${REDIS_PASSWORD}

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - hrvault-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: hrvault-mailpit

    restart: unless-stopped

    ports:
      - "1025:1025"
      - "8025:8025"

    networks:
      - hrvault-network

  seq:
    image: datalust/seq:latest
    container_name: hrvault-seq

    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_ADMIN_PASSWORD}

    ports:
      - "5341:5341"
      - "8081:80"

    volumes:
      - seq_data:/data

    networks:
      - hrvault-network

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:
  redis_data:
  seq_data:

networks:
  hrvault-network:
    driver: bridge